### ISSUE TITLE
Test coverage with coveralls and cobertura

### ISSUE THREAD

**Issue by ylverhoog** [tygron-virtual-humans/Integration-runtime#21]

**Comment by ylverhoog** [comment]
follow directions in https://github.com/trautonen/coveralls-maven-plugin/blob/master/README.md

**Comment by mspanoghe** [comment]
Gaan we dit nog doen? Zo niet, closen?

**Comment by berndkr** [comment]
Niet meer handig aangezien het project bijna gedaan is.
