### ISSUE TITLE
Taak "Goals for agent must be registered in GAM + testing"

### ISSUE THREAD

**Issue by RolfStarre** [tygron-virtual-humans/Integration-runtime#3]
@jwooning  

Edit: De Goal goals moeten in runtime aan de GAM instance worden toegevoegd.

En natuurlijk moet het worden getest.

**Comment by yannick** [comment]
ich verstehe keine wort

**Comment by RolfStarre** [comment]
Worden nu toegevoegd aan Gam instance als je de goals in een door onze parser te parsen bestand zet. 

Moet nog wel getest worden.

En Maven herkent de languagetools classes niet??

**Comment by RolfStarre** [comment]
Nu ook getest.
